const puzzle = getParameterByName("name");
const gameSongs = games[puzzle]["puzzle"];
const gameTitle = games[puzzle]["title"];
const songs = Object.keys(gameSongs);
const rows = 4;
const cols = 5;
let lives = 3;
let numCorrect = 0;
let progressBarValue = 0;
let score = 0;
let chewable = true;
let progressBarPercentage;
let numToWin;
let ten_minutes = 0;
let minutes = 1;
let ten_seconds = 0;
let seconds = 0;
let blinking = false;
let blink;
const clock = setInterval(function(){setTime(ten_minutes, minutes, ten_seconds, --seconds)}, 1000);
const timer = document.getElementById('timer');